"""empty message

Revision ID: 04341a08a711
Revises: d491eeb7e2d9
Create Date: 2019-09-10 18:24:03.181233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04341a08a711'
down_revision = 'd491eeb7e2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'follows', ['follower_id'])
    op.create_unique_constraint(None, 'follows', ['followed_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'follows', type_='unique')
    op.drop_constraint(None, 'follows', type_='unique')
    # ### end Alembic commands ###
