"""empty message

Revision ID: 94996ee364ae
Revises: 
Create Date: 2019-09-09 11:42:26.259061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94996ee364ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'view_count')
    # ### end Alembic commands ###
