"""empty message

Revision ID: aa579d7f0b1f
Revises: 04341a08a711
Create Date: 2019-09-11 09:30:08.982465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa579d7f0b1f'
down_revision = '04341a08a711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('follows_followed_id_key', 'follows', type_='unique')
    op.drop_constraint('follows_follower_id_key', 'follows', type_='unique')
    op.drop_column('follows', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint('follows_follower_id_key', 'follows', ['follower_id'])
    op.create_unique_constraint('follows_followed_id_key', 'follows', ['followed_id'])
    # ### end Alembic commands ###
